import {
  pgTable,
  text,
  integer,
  timestamp,
  pgEnum,
  jsonb,
} from 'drizzle-orm/pg-core';
import { organizations } from './organizations.schema.js';
import { customsEntries } from './customs-entries.schema.js';

export const rectificationStatusEnum = pgEnum('rectification_status', [
  'DRAFT', // Being prepared
  'SUBMITTED', // Filed with customs
  'APPROVED', // Approved by SAT
  'REJECTED', // Rejected by SAT
  'CANCELLED', // Cancelled before filing
]);

export const rectificationReasonEnum = pgEnum('rectification_reason', [
  'DATA_ERROR', // Error en datos del pedimento
  'TARIFF_FRACTION', // Corrección de fracción arancelaria
  'VALUE_ADJUSTMENT', // Ajuste de valor en aduana
  'DESCRIPTION_CORRECTION', // Corrección de descripción de mercancía
  'QUANTITY_ADJUSTMENT', // Ajuste de cantidad
  'REGIME_CHANGE', // Cambio de régimen
  'TAX_CORRECTION', // Corrección de contribuciones
  'PARTY_DATA', // Corrección de datos de partes
  'OTHER',
]);

// customs_rectifications — formal pedimento rectifications (complementos/rectificaciones)
// A rectification is a formal amendment to a cleared customs entry.
// Mexican law (Ley Aduanera Art. 89) allows rectification of certain data
// after the entry has been released, subject to conditions and time limits.
export const customsRectifications = pgTable('customs_rectifications', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  organizationId: text('organization_id')
    .notNull()
    .references(() => organizations.id),

  // The original entry being rectified
  originalEntryId: text('original_entry_id')
    .notNull()
    .references(() => customsEntries.id, { onDelete: 'restrict' }),

  // The new entry created as rectification (generated by this rectification)
  rectificationEntryId: text('rectification_entry_id').references(
    () => customsEntries.id,
  ),

  // Rectification sequence number (1st, 2nd, etc.)
  sequenceNumber: integer('sequence_number').notNull().default(1),

  status: rectificationStatusEnum('status').notNull().default('DRAFT'),
  reason: rectificationReasonEnum('reason').notNull(),
  reasonDescription: text('reason_description').notNull(),

  // Fields being modified (JSONB for flexibility)
  // Stores the diff: { field: { from: oldValue, to: newValue } }
  modifiedFields: jsonb('modified_fields'),

  // Filing details
  filedAt: timestamp('filed_at', { withTimezone: true }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  rejectedAt: timestamp('rejected_at', { withTimezone: true }),

  // SAT reference
  satAcknowledgmentNumber: text('sat_acknowledgment_number'),
  satRejectionReason: text('sat_rejection_reason'),

  internalNotes: text('internal_notes'),
  metadata: jsonb('metadata'),

  createdById: text('created_by_id').notNull(),
  updatedById: text('updated_by_id'),

  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// Rectification field changes — detailed diff of each changed field
export const rectificationFieldChanges = pgTable(
  'rectification_field_changes',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    rectificationId: text('rectification_id')
      .notNull()
      .references(() => customsRectifications.id, { onDelete: 'cascade' }),

    fieldPath: text('field_path').notNull(), // e.g., "items[0].tariffFraction"
    fieldLabel: text('field_label').notNull(), // Human-readable field name
    oldValue: text('old_value'),
    newValue: text('new_value'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
);
