import type { MembershipRole } from '../../database/schema/index.js';
import { PERMISSION, type Permission } from './permission.codes.js';

// Permissions are cumulative — each higher role includes everything below it.

const MEMBER_PERMISSIONS: Permission[] = [
  PERMISSION.ORGANIZATIONS_READ,
  PERMISSION.MEMBERS_READ,
  PERMISSION.USERS_READ,
  PERMISSION.CLIENTS_READ,
  PERMISSION.CLIENT_CONTACTS_READ,
  PERMISSION.CLIENT_ADDRESSES_READ,
  PERMISSION.OPERATIONS_READ,
  PERMISSION.OPERATIONS_COMMENT,
  PERMISSION.OPERATION_HISTORY_READ,
  PERMISSION.DOCUMENT_CATEGORIES_READ,
  PERMISSION.DOCUMENTS_READ,
  PERMISSION.DOCUMENTS_DOWNLOAD,
  PERMISSION.FINANCE_READ,
  PERMISSION.COMPLIANCE_READ,
  PERMISSION.COMPLIANCE_EVALUATE,
  PERMISSION.EXPORTS_READ,
  PERMISSION.IMPORTS_READ,
  PERMISSION.AI_READ,
  PERMISSION.AI_SEARCH,
  PERMISSION.AI_GENERATE_SUMMARY,
  PERMISSION.AI_VIEW_SIGNALS,
  PERMISSION.BILLING_READ,
  PERMISSION.USAGE_READ,
];

const ADMIN_PERMISSIONS: Permission[] = [
  ...MEMBER_PERMISSIONS,
  PERMISSION.MEMBERS_INVITE,
  PERMISSION.MEMBERS_REMOVE,
  PERMISSION.MEMBERS_UPDATE_ROLE,
  PERMISSION.ROLES_READ,
  PERMISSION.AUDIT_LOGS_READ,
  PERMISSION.CLIENTS_CREATE,
  PERMISSION.CLIENTS_UPDATE,
  PERMISSION.CLIENT_CONTACTS_CREATE,
  PERMISSION.CLIENT_CONTACTS_UPDATE,
  PERMISSION.CLIENT_ADDRESSES_CREATE,
  PERMISSION.CLIENT_ADDRESSES_UPDATE,
  PERMISSION.OPERATIONS_CREATE,
  PERMISSION.OPERATIONS_UPDATE,
  PERMISSION.OPERATIONS_ASSIGN,
  PERMISSION.OPERATIONS_CHANGE_STATUS,
  PERMISSION.DOCUMENT_CATEGORIES_CREATE,
  PERMISSION.DOCUMENT_CATEGORIES_UPDATE,
  PERMISSION.DOCUMENTS_CREATE,
  PERMISSION.DOCUMENTS_UPDATE,
  PERMISSION.DOCUMENTS_UPLOAD_VERSION,
  PERMISSION.FINANCE_CREATE_CHARGE,
  PERMISSION.FINANCE_UPDATE_CHARGE,
  PERMISSION.FINANCE_CREATE_ADVANCE,
  PERMISSION.FINANCE_UPDATE_ADVANCE,
  PERMISSION.FINANCE_GENERATE_EXPENSE_ACCOUNT,
  PERMISSION.COMPLIANCE_MANAGE_RULE_SETS,
  PERMISSION.COMPLIANCE_MANAGE_DOCUMENT_REQUIREMENTS,
  PERMISSION.COMPLIANCE_MANAGE_STATUS_RULES,
  PERMISSION.INTEGRATIONS_READ,
  PERMISSION.INTEGRATIONS_MANAGE,
  PERMISSION.INTEGRATIONS_RUN,
  PERMISSION.INTEGRATIONS_LOGS_READ,
  PERMISSION.EXPORTS_GENERATE,
  PERMISSION.IMPORTS_RUN,
  PERMISSION.FEATURE_FLAGS_READ,
];

const OWNER_PERMISSIONS: Permission[] = [
  ...ADMIN_PERMISSIONS,
  PERMISSION.ORGANIZATIONS_UPDATE,
  PERMISSION.ORGANIZATIONS_DELETE,
  PERMISSION.ROLES_MANAGE,
  PERMISSION.CLIENTS_DELETE,
  PERMISSION.CLIENT_CONTACTS_DELETE,
  PERMISSION.CLIENT_ADDRESSES_DELETE,
  PERMISSION.OPERATIONS_DELETE,
  PERMISSION.DOCUMENT_CATEGORIES_DELETE,
  PERMISSION.DOCUMENTS_DELETE,
  PERMISSION.FINANCE_DELETE_CHARGE,
  PERMISSION.FINANCE_DELETE_ADVANCE,
  PERMISSION.PORTAL_ACCESS_MANAGE,
  PERMISSION.PLANS_READ,
  PERMISSION.FEATURE_FLAGS_MANAGE,
];

// CLIENT role: external users accessing the portal for a specific client.
// Only portal-scoped permissions — no internal management access.
const CLIENT_PERMISSIONS: Permission[] = [
  PERMISSION.PORTAL_READ,
  PERMISSION.PORTAL_OPERATIONS_READ,
  PERMISSION.PORTAL_DOCUMENTS_READ,
  PERMISSION.PORTAL_DOCUMENTS_DOWNLOAD,
  PERMISSION.PORTAL_COMMENTS_READ,
];

export const ROLE_PERMISSIONS: Record<MembershipRole, readonly Permission[]> = {
  OWNER: OWNER_PERMISSIONS,
  ADMIN: [...ADMIN_PERMISSIONS, PERMISSION.PORTAL_ACCESS_MANAGE],
  MEMBER: MEMBER_PERMISSIONS,
  CLIENT: CLIENT_PERMISSIONS,
};
